In [3]:
pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in C:\Users\mrsanu\AppData\Roaming\Python\Python313\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import numpy as np
import pandas as pd
import pyodbc

In [ ]:
# #CREATE A CONNECTION TO MY DATABASE


# #DATABASE DETAILS
# server = 'MRSANU'
# database = 'jobdata'
# username = "MRSANU\\Mohd Sana"
# password = 'Sana#246810'

# #TABLES_NAME
# table_names = ['company_dim2','job_postings_fact2','skills_dim2','skills_job_dim2']
# #CONNECTION STRING
# conn_str =  f'DRIVER={{ODBC Driver 17 for SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}'

# #CONNECT TO MS-SQL SERVER
# conn= pyodbc.connect(conn_str)
# print("Connection Successfull")

# #DICTIONARY TO STORE ALL THE TABLES
# dataframes= {}

# for table_name in table_names:
#     query= f"Select * from {table_name}"
#     df= pd.read_sql(query, conn)
#     dataframes[table_name]= df

# conn.close()

InterfaceError: ('28000', "[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'MRSANU\\Mohd Sana'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user 'MRSANU\\Mohd Sana'. (18456)")

In [2]:
import pandas as pd
import pyodbc

server = 'MRSANU'
database = 'jobdata'

# Connection string using Windows Integrated Security
conn_str = (
    f'DRIVER={{ODBC Driver 17 for SQL Server}};'
    f'SERVER={server};'
    f'DATABASE={database};'
    f'Trusted_Connection=yes;'
)

conn = pyodbc.connect(conn_str)
print("Connection Successful")

table_names = ['company_dim2', 'job_postings_fact2', 'skills_dim2', 'skills_job_dim2']
dataframes = {}

for table_name in table_names:
    query = f"SELECT * FROM {table_name}"
    dataframes[table_name] = pd.read_sql(query, conn)

conn.close()

Connection Successful

C:\Users\mrsanu\AppData\Local\Temp\ipykernel_2900\1520433422.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  dataframes[table_name] = pd.read_sql(query, conn)

In [3]:
company= dataframes['company_dim2']
company.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140033 entries, 0 to 140032
Data columns (total 5 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   company_id   140033 non-null  int64
 1   name         140032 non-null  object
 2   link         54032 non-null   object
 3   link_google  140009 non-null  object
 4   thumbnail    81112 non-null   object
dtypes: int64(1), object(4)
memory usage: 5.3+ MB

In [4]:
company= dataframes['company_dim2']
Job_posting= dataframes['job_postings_fact2']
skill_id = dataframes['skills_job_dim2']
skills = dataframes['skills_dim2']

In [5]:
merge = pd.merge(company, Job_posting, on="company_id", how= "left")

In [6]:
merge = pd.merge(merge, skill_id, on="job_id", how= "left")

In [7]:
merge = pd.merge(merge, skills, on="skill_id", how= "left")

In [10]:
merge

,company_id,name,link,link_google,thumbnail,job_id,job_title_short,job_title,job_location,job_via,...,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,skill_id,skills,type
0,0,Cryptology,None,https://www.google.com/search?sca_esv=56842508...,https://encrypted-tbn0.gstatic.com/images?q=tb...,0,Data Analyst,Marketing Data Analyst,Anywhere,via LinkedIn,...,2023-09-25 17:46:06,False,False,Serbia,None,NaN,NaN,0.0,sql,programming
1,0,Cryptology,None,https://www.google.com/search?sca_esv=56842508...,https://encrypted-tbn0.gstatic.com/images?q=tb...,0,Data Analyst,Marketing Data Analyst,Anywhere,via LinkedIn,...,2023-09-25 17:46:06,False,False,Serbia,None,NaN,NaN,1.0,python,programming
2,0,Cryptology,None,https://www.google.com/search?sca_esv=56842508...,https://encrypted-tbn0.gstatic.com/images?q=tb...,923232,Data Analyst,Marketing Data Analyst,Anywhere,via LinkedIn,...,2023-09-25 17:51:21,False,False,Spain,None,NaN,NaN,0.0,sql,programming
3,0,Cryptology,None,https://www.google.com/search?sca_esv=56842508...,https://encrypted-tbn0.gstatic.com/images?q=tb...,923232,Data Analyst,Marketing Data Analyst,Anywhere,via LinkedIn,...,2023-09-25 17:51:21,False,False,Spain,None,NaN,NaN,1.0,python,programming
4,0,Cryptology,None,https://www.google.com/search?sca_esv=56842508...,https://encrypted-tbn0.gstatic.com/images?q=tb...,1819517,Data Analyst,Marketing Data Analyst,"Madrid, Spain",via BeBee,...,2023-10-10 10:32:19,False,False,Spain,None,NaN,NaN,0.0,sql,programming
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1434220,787652,Rotary Engineering Pte. Ltd.,http://www.rotaryeng.com.sg/,None,https://encrypted-tbn0.gstatic.com/images?q=tb...,1424742,Senior Data Scientist,Senior Design Engineer (Instrumentation),Singapura,melalui Recruit.net,...,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,NaN,NaN,NaN
1434221,787674,Pure App,None,None,https://encrypted-tbn0.gstatic.com/images?q=tb...,549918,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",melalui Top County Careers,...,2023-03-13 06:19:07,False,False,Germany,None,NaN,NaN,NaN,NaN,NaN
1434222,787675,Staff-UP Consulting Group,None,None,None,782857,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",melalui Melga,...,2023-03-12 06:31:13,False,False,Kazakhstan,None,NaN,NaN,NaN,NaN,NaN
1434223,787680,CAREERSTAR INTERNATIONAL PTE. LTD.,None,None,https://encrypted-tbn0.gstatic.com/images?q=tb...,828965,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,...,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,NaN,NaN,NaN
1434224,787681,Lendlease Corporation,http://www.lendlease.com/,None,https://encrypted-tbn0.gstatic.com/images?q=tb...,1146883,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,...,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,NaN,NaN,NaN

In [8]:
merge.columns

Index(['company_id', 'name', 'link', 'link_google', 'thumbnail', 'job_id',
       'job_title_short', 'job_title', 'job_location', 'job_via',
       'job_schedule_type', 'job_work_from_home', 'search_location',
       'job_posted_date', 'job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'skill_id', 'skills', 'type'],
      dtype='object')

In [9]:
columns_to_be_dropped = ['link', 'link_google', 'thumbnail','job_via','job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'skill_id','type']

In [23]:
columns_to_be_dropped

['link',
 'link_google',
 'thumbnail',
 'job_via',
 'job_no_degree_mention',
 'job_health_insurance',
 'job_country',
 'salary_rate',
 'salary_year_avg',
 'salary_hour_avg',
 'skill_id',
 'type']

In [11]:
# merge.drop(columns=columns_to_be_dropped,inplace=True)

merge.drop(columns=columns_to_be_dropped, inplace=True, errors='ignore')

In [18]:
merge.columns

Index(['company_id', 'name', 'job_id', 'job_title_short', 'job_title',
       'job_location', 'job_schedule_type', 'job_work_from_home',
       'search_location', 'job_posted_date', 'skills'],
      dtype='object')

In [19]:
merge

,company_id,name,job_id,job_title_short,job_title,job_location,job_schedule_type,job_work_from_home,search_location,job_posted_date,skills
0,0,Cryptology,0,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Serbia,2023-09-25 17:46:06,sql
1,0,Cryptology,0,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Serbia,2023-09-25 17:46:06,python
2,0,Cryptology,923232,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Spain,2023-09-25 17:51:21,sql
3,0,Cryptology,923232,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Spain,2023-09-25 17:51:21,python
4,0,Cryptology,1819517,Data Analyst,Marketing Data Analyst,"Madrid, Spain",Full-time,False,Spain,2023-10-10 10:32:19,sql
...,...,...,...,...,...,...,...,...,...,...,...
1434220,787652,Rotary Engineering Pte. Ltd.,1424742,Senior Data Scientist,Senior Design Engineer (Instrumentation),Singapura,Kontraktor,False,Singapore,2023-03-13 06:16:16,NaN
1434221,787674,Pure App,549918,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,NaN
1434222,787675,Staff-UP Consulting Group,782857,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",Pekerjaan tetap,False,Kazakhstan,2023-03-12 06:31:13,NaN
1434223,787680,CAREERSTAR INTERNATIONAL PTE. LTD.,828965,Software Engineer,DevOps Engineer,Singapura,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,NaN
1434224,787681,Lendlease Corporation,1146883,Business Analyst,Commercial Analyst - Start Now,Malaysia,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,NaN

In [20]:
merge['skills']= merge['skills'].fillna('').astype(str)

In [21]:
merge

,company_id,name,job_id,job_title_short,job_title,job_location,job_schedule_type,job_work_from_home,search_location,job_posted_date,skills
0,0,Cryptology,0,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Serbia,2023-09-25 17:46:06,sql
1,0,Cryptology,0,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Serbia,2023-09-25 17:46:06,python
2,0,Cryptology,923232,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Spain,2023-09-25 17:51:21,sql
3,0,Cryptology,923232,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Spain,2023-09-25 17:51:21,python
4,0,Cryptology,1819517,Data Analyst,Marketing Data Analyst,"Madrid, Spain",Full-time,False,Spain,2023-10-10 10:32:19,sql
...,...,...,...,...,...,...,...,...,...,...,...
1434220,787652,Rotary Engineering Pte. Ltd.,1424742,Senior Data Scientist,Senior Design Engineer (Instrumentation),Singapura,Kontraktor,False,Singapore,2023-03-13 06:16:16,
1434221,787674,Pure App,549918,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,
1434222,787675,Staff-UP Consulting Group,782857,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",Pekerjaan tetap,False,Kazakhstan,2023-03-12 06:31:13,
1434223,787680,CAREERSTAR INTERNATIONAL PTE. LTD.,828965,Software Engineer,DevOps Engineer,Singapura,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,
1434224,787681,Lendlease Corporation,1146883,Business Analyst,Commercial Analyst - Start Now,Malaysia,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,

In [22]:
final_dataframe = merge.groupby(['company_id', 'name', 'job_id', 'job_title_short', 'job_title',
       'job_location', 'job_schedule_type', 'job_work_from_home',
       'search_location', 'job_posted_date'])['skills'].agg(','.join).reset_index()

In [23]:
final_dataframe

,company_id,name,job_id,job_title_short,job_title,job_location,job_schedule_type,job_work_from_home,search_location,job_posted_date,skills
0,0,Cryptology,0,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Serbia,2023-09-25 17:46:06,"sql,python"
1,0,Cryptology,923232,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,Spain,2023-09-25 17:51:21,"sql,python"
2,0,Cryptology,1695656,Data Analyst,Marketing Data Analyst,Anywhere,Full-time,True,United Kingdom,2023-09-25 18:11:19,
3,0,Cryptology,1819517,Data Analyst,Marketing Data Analyst,"Madrid, Spain",Full-time,False,Spain,2023-10-10 10:32:19,"sql,python"
4,1,Edraak,55,Cloud Engineer,Storage and Virtualization Engineer,"Kuwait City, Kuwait",Full-time,False,Kuwait,2023-07-30 17:49:18,
...,...,...,...,...,...,...,...,...,...,...,...
773931,787652,Rotary Engineering Pte. Ltd.,1424742,Senior Data Scientist,Senior Design Engineer (Instrumentation),Singapura,Kontraktor,False,Singapore,2023-03-13 06:16:16,
773932,787674,Pure App,549918,Senior Data Engineer,Senior Data Engineer,"Berlin, Jerman",Pekerjaan tetap,False,Germany,2023-03-13 06:19:07,
773933,787675,Staff-UP Consulting Group,782857,Business Analyst,PreSales Engineer,"Almaty, Kazakhstan",Pekerjaan tetap,False,Kazakhstan,2023-03-12 06:31:13,
773934,787680,CAREERSTAR INTERNATIONAL PTE. LTD.,828965,Software Engineer,DevOps Engineer,Singapura,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,
773935,787681,Lendlease Corporation,1146883,Business Analyst,Commercial Analyst - Start Now,Malaysia,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,

In [ ]:
### final code for power bi 
import numpy as np
import pandas as pd
import pyodbc

import pandas as pd
import pyodbc

server = 'MRSANU'
database = 'jobdata'

# Connection string using Windows Integrated Security
conn_str = (
    f'DRIVER={{ODBC Driver 17 for SQL Server}};'
    f'SERVER={server};'
    f'DATABASE={database};'
    f'Trusted_Connection=yes;'
)

conn = pyodbc.connect(conn_str)
print("Connection Successful")

table_names = ['company_dim2', 'job_postings_fact2', 'skills_dim2', 'skills_job_dim2']
dataframes = {}

for table_name in table_names:
    query = f"SELECT * FROM {table_name}"
    dataframes[table_name] = pd.read_sql(query, conn)

conn.close()

company= dataframes['company_dim2']
Job_posting= dataframes['job_postings_fact2']
skill_id = dataframes['skills_job_dim2']
skills = dataframes['skills_dim2']


merge = pd.merge(company, Job_posting, on="company_id", how= "left")
merge = pd.merge(merge, skill_id, on="job_id", how= "left")
merge = pd.merge(merge, skills, on="skill_id", how= "left")


columns_to_be_dropped = ['link', 'link_google', 'thumbnail','job_via','job_no_degree_mention', 'job_health_insurance',
       'job_country', 'salary_rate', 'salary_year_avg', 'salary_hour_avg',
       'skill_id','type']

merge.drop(columns=columns_to_be_dropped, inplace=True, errors='ignore')

merge['skills']= merge['skills'].fillna('').astype(str)


final_dataframe = merge.groupby(['company_id', 'name', 'job_id', 'job_title_short', 'job_title',
       'job_location', 'job_schedule_type', 'job_work_from_home',
       'search_location', 'job_posted_date'])['skills'].agg(','.join).reset_index()